#!/usr/bin/env python3
from pathlib import Path
import re, sys, yaml
ROOT=Path(__file__).resolve().parents[1]
CANON=(ROOT/"docs/canon/RippleLogic_v12.5_Canon.md").read_text(encoding="utf-8")
REG=yaml.safe_load((ROOT/"docs/implementation/CANONICAL_AUDIT_FLAG_REGISTRY_v1.0.yaml").read_text(encoding="utf-8"))
tokens={x["token"] for x in REG["flags"]}
required={
"RIGHTS_CELL_MASKED_INVALID","CATASTROPHE_CELL_MASKED_INVALID","RIGHTS_CELL_OMITTED_INVALID",
"MANDATORY_TAIL_CATEGORY_MISSING","MANDATORY_TAIL_PROB_FLOOR_VIOLATION","SCENARIO_LIBRARY_MIN_EXCEPTION",
"CONTAINMENT_UCI_UNAVAILABLE","KERNEL_HUMILITY_FALLBACK","KERNEL_EVIDENCE_COVERAGE_INSUFFICIENT",
"NUMERIC_OVERFLOW","SUBGROUP_LIMITATION","TAIL_EMERGENCY_MODE_INVOKED","TAIL_EMERGENCY_REFUSED",
"JUDGMENT_CALL_UCI_UNAVAILABLE","JUDGMENT_CALL_TIEBREAK_NONDECISIVE","MPS_HYPOTHESIS_SENSITIVE",
"RLS_NO_ACTIVE_MASS","UNCERTAINTY_DECISIVENESS_SENSITIVE","PLSS_PROMINENCE_SENSITIVE",
"CLAIM_EXCEEDS_CLOSURE_BOUNDARY","CATEGORY_COLLAPSE_FLAG","PCC_MATURITY_SURFACE_INCOMPLETE",
"REALITY_GROUNDING_RECORD_MISSING","REALITY_GROUNDING_STATUS_UNSUPPORTED",
"NORMATIVE_INPUT_PROVENANCE_MISSING","COMPUTABLE_BUT_INADMISSIBLE"}
missing=sorted(required-tokens)
not_in_canon=sorted(t for t in tokens if t not in CANON)
if missing or not_in_canon:
 print("AUDIT FLAG REGISTRY: FAIL")
 if missing: print("missing:",missing)
 if not_in_canon: print("registry tokens absent from Canon:",not_in_canon)
 sys.exit(1)
print(f"AUDIT FLAG REGISTRY: PASS ({len(tokens)} controlling tokens)")
