name: Bug report
description: Report a problem in the spec, packaging, or release artifacts
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please reference the exact release version and file path.
        Example: `releases/v8.1_2026-02-14/<file>`
  - type: input
    id: version
    attributes:
      label: Release version / tag
      placeholder: "v8.1 (2026-02-14)"
    validations:
      required: true
  - type: input
    id: file
    attributes:
      label: File path
      placeholder: "releases/v8.1_2026-02-14/..."
    validations:
      required: true
  - type: textarea
    id: observed
    attributes:
      label: What you observed
      description: Include exact wording, screenshots, or hashes when relevant.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What you expected
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Why this matters (risk / rights / audit clarity)
      description: Explain implications for implementers or evaluators.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix (optional)
    validations:
      required: false
